name: pkg Build openssh

on:
  schedule:
     - cron: "30 2 3 * *"
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-openssh-server:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    name: Package and Publish openssh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/remote/ssh/openssh
          file: ${{ github.workspace }}/remote/ssh/openssh/CustomBuild.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}


  build-cve-2019-6111-server:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    name: Package and Publish openssh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/remote/ssh/openssh
          file: ${{ github.workspace }}/remote/ssh/openssh/CVE-2019-6111.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}