name: pkg Release open62541 LDS to GHCR

# manual workflow, alternatively when generating new tags for the release
on:
  schedule:
     - cron: "30 2 3 * *"
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# annotation keys are explained here for metadata related infos:
# https://github.com/opencontainers/image-spec/blob/main/annotations.md

jobs:
  publish-lds-open62541-server:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    name: Package and Publish LDS open62541 Server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

# the licenses are fetched from the local git repository somehow...
# we dont need to setup a license field as part of the labels
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/laboratory-for-safe-and-secure-systems/open62541-lds-server
          tags: | 
            type=raw,value=latest
          labels: |
            maintainer=Frozenbitz
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=KRITIS3M-open62541-lds
            org.opencontainers.image.description=Testing a custom lds version
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/lds/lds-open62541-server/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/lds/lds-open62541-server

          annotations: |
            maintainer=Frozenbitz
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=KRITIS3M-open62541-lds
            org.opencontainers.image.description=Testing a custom lds version
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/lds/lds-open62541-server/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/lds/lds-open62541-server

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/opcua/lds/lds-open62541-server
          build-contexts: |
            container_context=${{ github.workspace }}/opcua/lds/lds-open62541-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}