name: pkg Release UA Standard dotnet to GHCR

# manual workflow, alternatively when generating new tags for the release
on:
  schedule:
     - cron: "30 2 3 * *"
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# annotation keys are explained here for metadata related infos:
# https://github.com/opencontainers/image-spec/blob/main/annotations.md

jobs:
  publish-dotnet-server:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    name: Package and Publish .NET
    steps:
      - name: Checkout
        uses: actions/checkout@v4

# the licenses are fetched from the local git repository somehow...
# we dont need to setup a license field as part of the labels
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner,, }}/dotnet-server
          tags: | 
            type=raw,value=latest
          labels: |
            maintainer=Frozenbitz
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=KRITIS3M-dotnet-server
            org.opencontainers.image.description=A OPC UA test server preconfigured to run a custom NodeSet2.xml for pentesting
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/server/dotnet-NETStandard/latest/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/server/dotnet-NETStandard/latest

          annotations: |
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=KRITIS3M-dotnet-server
            org.opencontainers.image.description=A OPC UA test server preconfigured to run a custom NodeSet2.xml for pentesting
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/server/dotnet-NETStandard/latest/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-images/blob/main/opcua/server/dotnet-NETStandard/latest


      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/opcua/server/dotnet-NETStandard/latest
          build-args: |
            NODESET_MODEL=FullSystem.PredefinedNodes.uanodes
          build-contexts: |
            container_context=${{ github.workspace }}/opcua/server/dotnet-NETStandard/latest
            nodeset_context=${{ github.workspace }}/meta/demo-nodeset2
            companion_context=${{ github.workspace }}/meta/companion-specifications
            configuration_context=${{ github.workspace }}/meta/server-configuration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}